<a href="https://colab.research.google.com/github/royarkaofficial/DataOps-Lab8-31th-Dec-2024-Feature-Engineering/blob/main/Copy_of_Lab10_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
#Load the dataset into the dataframe

df = pd.read_csv('/content/sample_data/sample_car_sales_data.csv')
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  
0  Luxury model with premium features  
1    Low mileage, excellent condition  
2    Low mileage, excellent condition  
3        Clean interior, no accidents  
4    Low mileage, excellent condition

**Creating the new features**

In [ ]:
#Method 1 : Interaction term
df['price_per_horsepower'] = df['Price'] / df['Horsepower']
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  price_per_horsepower  
0  Luxury model with premium features             68.529240  
1    Low mileage, excellent condition             82.284091  
2    Low mileage, excellent condition            125.678063  
3        Clean interior, no accidents            180.384328  
4    Low mileage, excellent condition            164.593023

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
#Method 2 : Polynomial Features
num_col = ["Price","Horsepower"]

In [ ]:
poly = PolynomialFeatures(degree=2,include_bias=False)
# x = x and (x)2

In [ ]:
poly_feature = poly.fit_transform(df[num_col])
poly_feature

array([[2.34370000e+04, 3.42000000e+02, 5.49292969e+08, 8.01545400e+06,
        1.16964000e+05],
       [2.17230000e+04, 2.64000000e+02, 4.71888729e+08, 5.73487200e+06,
        6.96960000e+04],
       [4.41130000e+04, 3.51000000e+02, 1.94595677e+09, 1.54836630e+07,
        1.23201000e+05],
       [4.83430000e+04, 2.68000000e+02, 2.33704565e+09, 1.29559240e+07,
        7.18240000e+04],
       [2.83100000e+04, 1.72000000e+02, 8.01456100e+08, 4.86932000e+06,
        2.95840000e+04],
       [3.61440000e+04, 2.75000000e+02, 1.30638874e+09, 9.93960000e+06,
        7.56250000e+04],
       [2.36650000e+04, 2.14000000e+02, 5.60032225e+08, 5.06431000e+06,
        4.57960000e+04],
       [4.53380000e+04, 2.51000000e+02, 2.05553424e+09, 1.13798380e+07,
        6.30010000e+04],
       [2.81200000e+04, 2.87000000e+02, 7.90734400e+08, 8.07044000e+06,
        8.23690000e+04],
       [2.39400000e+04, 3.62000000e+02, 5.73123600e+08, 8.66628000e+06,
        1.31044000e+05],
       [3.17570000e+04, 2.7200

In [ ]:
df_poly = pd.DataFrame(poly_feature, columns = poly.get_feature_names_out(num_col))
df_poly.head()

Price  Horsepower       Price^2  Price Horsepower  Horsepower^2
0  23437.0       342.0  5.492930e+08         8015454.0      116964.0
1  21723.0       264.0  4.718887e+08         5734872.0       69696.0
2  44113.0       351.0  1.945957e+09        15483663.0      123201.0
3  48343.0       268.0  2.337046e+09        12955924.0       71824.0
4  28310.0       172.0  8.014561e+08         4869320.0       29584.0

**Categorical values**

In [ ]:
#Method 1 : Label encoding
from sklearn.preprocessing import LabelEncoder

In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sample_car_sales_data.csv')
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  
0  Luxury model with premium features  
1    Low mileage, excellent condition  
2    Low mileage, excellent condition  
3        Clean interior, no accidents  
4    Low mileage, excellent condition

In [ ]:
label_encoder = LabelEncoder()
df["Brand_encoded"] = label_encoder.fit_transform(df["Brand"])
df.head()
df

Price  Horsepower   Brand   Model Date_of_Sale  \
0    23437         342   Honda  Accord   2023-03-13   
1    21723         264  Toyota   Prius   2023-06-14   
2    44113         351   Honda   Civic   2024-03-04   
3    48343         268   Honda    CR-V   2024-10-12   
4    28310         172    Audi      A3   2024-03-24   
..     ...         ...     ...     ...          ...   
145  20079         308    Audi      Q5   2022-07-22   
146  23492         390   Honda    CR-V   2024-06-29   
147  22063         119     BMW      X3   2021-12-24   
148  32704         273     BMW      X5   2022-07-22   
149  18783         347    Audi      A3   2021-10-24   

                            Description  Brand_encoded  
0    Luxury model with premium features              3  
1      Low mileage, excellent condition              4  
2      Low mileage, excellent condition              3  
3          Clean interior, no accidents              3  
4      Low mileage, excellent condition              0  
..                                  ...            ...  
145         Sport package, fully loaded              0  
146  Luxury model with premium features              3  
147    Low mileage, excellent condition              1  
148         Sport package, fully loaded              1  
149    Low mileage, excellent condition              0  

[150 rows x 7 columns]

In [ ]:
df.drop(columns=["Brand"],inplace = True)
df.head()

Price  Horsepower   Model Date_of_Sale                         Description  \
0  23437         342  Accord   2023-03-13  Luxury model with premium features   
1  21723         264   Prius   2023-06-14    Low mileage, excellent condition   
2  44113         351   Civic   2024-03-04    Low mileage, excellent condition   
3  48343         268    CR-V   2024-10-12        Clean interior, no accidents   
4  28310         172      A3   2024-03-24    Low mileage, excellent condition   

   Brand_encoded  
0              3  
1              4  
2              3  
3              3  
4              0

In [ ]:
#Method 2 : One Hot enconding
from sklearn.preprocessing import OneHotEncoder

In [ ]:
OHE = OneHotEncoder(sparse_output=False)
#Sparse_matrix = zeros (memory efficient)
#Dense array (A regular Numpy array)
Mode_Encoded = OHE.fit_transform(df[["Model"]])
print(Mode_Encoded)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
df_Mode_encoded = pd.DataFrame(Mode_Encoded, columns = OHE.get_feature_names_out(["Model"]))
df_Mode_encoded.head()

Model_A3  Model_A4  Model_Accord  Model_CR-V  Model_Camry  Model_Civic  \
0       0.0       0.0           1.0         0.0          0.0          0.0   
1       0.0       0.0           0.0         0.0          0.0          0.0   
2       0.0       0.0           0.0         0.0          0.0          1.0   
3       0.0       0.0           0.0         1.0          0.0          0.0   
4       1.0       0.0           0.0         0.0          0.0          0.0   

   Model_Corolla  Model_Explorer  Model_Fiesta  Model_Fit  Model_Focus  \
0            0.0             0.0           0.0        0.0          0.0   
1            0.0             0.0           0.0        0.0          0.0   
2            0.0             0.0           0.0        0.0          0.0   
3            0.0             0.0           0.0        0.0          0.0   
4            0.0             0.0           0.0        0.0          0.0   

   Model_M3  Model_Mustang  Model_Prius  Model_Q5  Model_RAV4  Model_TT  \
0       0.0            0.0          0.0       0.0         0.0       0.0   
1       0.0            0.0          1.0       0.0         0.0       0.0   
2       0.0            0.0          0.0       0.0         0.0       0.0   
3       0.0            0.0          0.0       0.0         0.0       0.0   
4       0.0            0.0          0.0       0.0         0.0       0.0   

   Model_X3  Model_X5  Model_i8  
0       0.0       0.0       0.0  
1       0.0       0.0       0.0  
2       0.0       0.0       0.0  
3       0.0       0.0       0.0  
4       0.0       0.0       0.0

In [ ]:
df_Mode_encoded

Model_A3  Model_A4  Model_Accord  Model_CR-V  Model_Camry  Model_Civic  \
0         0.0       0.0           1.0         0.0          0.0          0.0   
1         0.0       0.0           0.0         0.0          0.0          0.0   
2         0.0       0.0           0.0         0.0          0.0          1.0   
3         0.0       0.0           0.0         1.0          0.0          0.0   
4         1.0       0.0           0.0         0.0          0.0          0.0   
..        ...       ...           ...         ...          ...          ...   
145       0.0       0.0           0.0         0.0          0.0          0.0   
146       0.0       0.0           0.0         1.0          0.0          0.0   
147       0.0       0.0           0.0         0.0          0.0          0.0   
148       0.0       0.0           0.0         0.0          0.0          0.0   
149       1.0       0.0           0.0         0.0          0.0          0.0   

     Model_Corolla  Model_Explorer  Model_Fiesta  Model_Fit  Model_Focus  \
0              0.0             0.0           0.0        0.0          0.0   
1              0.0             0.0           0.0        0.0          0.0   
2              0.0             0.0           0.0        0.0          0.0   
3              0.0             0.0           0.0        0.0          0.0   
4              0.0             0.0           0.0        0.0          0.0   
..             ...             ...           ...        ...          ...   
145            0.0             0.0           0.0        0.0          0.0   
146            0.0             0.0           0.0        0.0          0.0   
147            0.0             0.0           0.0        0.0          0.0   
148            0.0             0.0           0.0        0.0          0.0   
149            0.0             0.0           0.0        0.0          0.0   

     Model_M3  Model_Mustang  Model_Prius  Model_Q5  Model_RAV4  Model_TT  \
0         0.0            0.0          0.0       0.0         0.0       0.0   
1         0.0            0.0          1.0       0.0         0.0       0.0   
2         0.0            0.0          0.0       0.0         0.0       0.0   
3         0.0            0.0          0.0       0.0         0.0       0.0   
4         0.0            0.0          0.0       0.0         0.0       0.0   
..        ...            ...          ...       ...         ...       ...   
145       0.0            0.0          0.0       1.0         0.0       0.0   
146       0.0            0.0          0.0       0.0         0.0       0.0   
147       0.0            0.0          0.0       0.0         0.0       0.0   
148       0.0            0.0          0.0       0.0         0.0       0.0   
149       0.0            0.0          0.0       0.0         0.0       0.0   

     Model_X3  Model_X5  Model_i8  
0         0.0       0.0       0.0  
1         0.0       0.0       0.0  
2         0.0       0.0       0.0  
3         0.0       0.0       0.0  
4         0.0       0.0       0.0  
..        ...       ...       ...  
145       0.0       0.0       0.0  
146       0.0       0.0       0.0  
147       1.0       0.0       0.0  
148       0.0       1.0       0.0  
149       0.0       0.0       0.0  

[150 rows x 20 columns]

In [ ]:
df.drop(columns=["Model"],inplace = True)
df.head()

Price  Horsepower Date_of_Sale                         Description  \
0  23437         342   2023-03-13  Luxury model with premium features   
1  21723         264   2023-06-14    Low mileage, excellent condition   
2  44113         351   2024-03-04    Low mileage, excellent condition   
3  48343         268   2024-10-12        Clean interior, no accidents   
4  28310         172   2024-03-24    Low mileage, excellent condition   

   Brand_encoded  
0              3  
1              4  
2              3  
3              3  
4              0

In [ ]:
df = pd.concat([df,df_Mode_encoded],axis=1)
df.head()

Price  Horsepower Date_of_Sale                         Description  \
0  23437         342   2023-03-13  Luxury model with premium features   
1  21723         264   2023-06-14    Low mileage, excellent condition   
2  44113         351   2024-03-04    Low mileage, excellent condition   
3  48343         268   2024-10-12        Clean interior, no accidents   
4  28310         172   2024-03-24    Low mileage, excellent condition   

   Brand_encoded  Model_A3  Model_A4  Model_Accord  Model_CR-V  Model_Camry  \
0              3       0.0       0.0           1.0         0.0          0.0   
1              4       0.0       0.0           0.0         0.0          0.0   
2              3       0.0       0.0           0.0         0.0          0.0   
3              3       0.0       0.0           0.0         1.0          0.0   
4              0       1.0       0.0           0.0         0.0          0.0   

   ...  Model_Focus  Model_M3  Model_Mustang  Model_Prius  Model_Q5  \
0  ...          0.0       0.0            0.0          0.0       0.0   
1  ...          0.0       0.0            0.0          1.0       0.0   
2  ...          0.0       0.0            0.0          0.0       0.0   
3  ...          0.0       0.0            0.0          0.0       0.0   
4  ...          0.0       0.0            0.0          0.0       0.0   

   Model_RAV4  Model_TT  Model_X3  Model_X5  Model_i8  
0         0.0       0.0       0.0       0.0       0.0  
1         0.0       0.0       0.0       0.0       0.0  
2         0.0       0.0       0.0       0.0       0.0  
3         0.0       0.0       0.0       0.0       0.0  
4         0.0       0.0       0.0       0.0       0.0  

[5 rows x 25 columns]

In [ ]:
df.to_csv("Encoded_car_sales_data.csv")

**Handling Temporal Features(Date and Time based info)**

In [ ]:
df = pd.read_csv('/content/sample_data/sample_car_sales_data.csv')
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  
0  Luxury model with premium features  
1    Low mileage, excellent condition  
2    Low mileage, excellent condition  
3        Clean interior, no accidents  
4    Low mileage, excellent condition

In [ ]:
print(df["Date_of_Sale"].dtypes)

object


In [ ]:
df["Date_of_Sale"] = pd.to_datetime(df["Date_of_Sale"])
print(df["Date_of_Sale"].dtypes)

datetime64[ns]


In [ ]:
#Extract Year , Month and Day from Date of Sale
df["Sales_Year"] = df["Date_of_Sale"].dt.year
df["Sales_Month"] = df["Date_of_Sale"].dt.month
df["Sales_Day"] = df["Date_of_Sale"].dt.day
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  Sales_Year  Sales_Month  Sales_Day  
0  Luxury model with premium features        2023            3         13  
1    Low mileage, excellent condition        2023            6         14  
2    Low mileage, excellent condition        2024            3          4  
3        Clean interior, no accidents        2024           10         12  
4    Low mileage, excellent condition        2024            3         24

In [ ]:
print(df["Sales_Year"].dtypes)

int32


In [ ]:
df.drop(columns=["Date_of_Sale"],inplace = True)
df.head()

Price  Horsepower   Brand   Model                         Description  \
0  23437         342   Honda  Accord  Luxury model with premium features   
1  21723         264  Toyota   Prius    Low mileage, excellent condition   
2  44113         351   Honda   Civic    Low mileage, excellent condition   
3  48343         268   Honda    CR-V        Clean interior, no accidents   
4  28310         172    Audi      A3    Low mileage, excellent condition   

   Sales_Year  Sales_Month  Sales_Day  
0        2023            3         13  
1        2023            6         14  
2        2024            3          4  
3        2024           10         12  
4        2024            3         24

**TF-IDF**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
df = pd.read_csv('/content/sample_data/sample_car_sales_data.csv')
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  
0  Luxury model with premium features  
1    Low mileage, excellent condition  
2    Low mileage, excellent condition  
3        Clean interior, no accidents  
4    Low mileage, excellent condition

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
desc_tfidf = tfidf.fit_transform(df["Description"])

In [ ]:
df_tfidf = pd.DataFrame(desc_tfidf.toarray(), columns = tfidf.get_feature_names_out())
df_tfidf.head()

accidents  clean  condition  excellent  features  fully  interior  loaded  \
0        0.0    0.0        0.0        0.0  0.447214    0.0       0.0     0.0   
1        0.0    0.0        0.5        0.5  0.000000    0.0       0.0     0.0   
2        0.0    0.0        0.5        0.5  0.000000    0.0       0.0     0.0   
3        0.5    0.5        0.0        0.0  0.000000    0.0       0.5     0.0   
4        0.0    0.0        0.5        0.5  0.000000    0.0       0.0     0.0   

   low    luxury  ...  mileage     model   no  one  owner  package   premium  \
0  0.0  0.447214  ...      0.0  0.447214  0.0  0.0    0.0      0.0  0.447214   
1  0.5  0.000000  ...      0.5  0.000000  0.0  0.0    0.0      0.0  0.000000   
2  0.5  0.000000  ...      0.5  0.000000  0.0  0.0    0.0      0.0  0.000000   
3  0.0  0.000000  ...      0.0  0.000000  0.5  0.0    0.0      0.0  0.000000   
4  0.5  0.000000  ...      0.5  0.000000  0.0  0.0    0.0      0.0  0.000000   

   sport  well      with  
0    0.0   0.0  0.447214  
1    0.0   0.0  0.000000  
2    0.0   0.0  0.000000  
3    0.0   0.0  0.000000  
4    0.0   0.0  0.000000  

[5 rows x 21 columns]

In [ ]:
df.drop(columns=["Description"],inplace = True)

In [ ]:
df = pd.concat([df,df_tfidf],axis=1)
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  accidents  clean  \
0  23437         342   Honda  Accord   2023-03-13        0.0    0.0   
1  21723         264  Toyota   Prius   2023-06-14        0.0    0.0   
2  44113         351   Honda   Civic   2024-03-04        0.0    0.0   
3  48343         268   Honda    CR-V   2024-10-12        0.5    0.5   
4  28310         172    Audi      A3   2024-03-24        0.0    0.0   

   condition  excellent  features  ...  mileage     model   no  one  owner  \
0        0.0        0.0  0.447214  ...      0.0  0.447214  0.0  0.0    0.0   
1        0.5        0.5  0.000000  ...      0.5  0.000000  0.0  0.0    0.0   
2        0.5        0.5  0.000000  ...      0.5  0.000000  0.0  0.0    0.0   
3        0.0        0.0  0.000000  ...      0.0  0.000000  0.5  0.0    0.0   
4        0.5        0.5  0.000000  ...      0.5  0.000000  0.0  0.0    0.0   

   package   premium  sport  well      with  
0      0.0  0.447214    0.0   0.0  0.447214  
1      0.0  0.000000    0.0   0.0  0.000000  
2      0.0  0.000000    0.0   0.0  0.000000  
3      0.0  0.000000    0.0   0.0  0.000000  
4      0.0  0.000000    0.0   0.0  0.000000  

[5 rows x 26 columns]

**Stop words Removal**

In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sample_car_sales_data.csv')
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  
0  Luxury model with premium features  
1    Low mileage, excellent condition  
2    Low mileage, excellent condition  
3        Clean interior, no accidents  
4    Low mileage, excellent condition

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def remove_stopwords(text):
 words = word_tokenize(text)
 filtered_words = [word for word in words if word.lower() not in stopwords.words('english')]
 return ' '.join(filtered_words)
  #Convert each word to lowecase (Incase-sensitive)

In [ ]:
df["filtered_description"] = df["Description"].apply(remove_stopwords)
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description               filtered_description  
0  Luxury model with premium features      Luxury model premium features  
1    Low mileage, excellent condition  Low mileage , excellent condition  
2    Low mileage, excellent condition  Low mileage , excellent condition  
3        Clean interior, no accidents         Clean interior , accidents  
4    Low mileage, excellent condition  Low mileage , excellent condition

**Bag of Words(BOW)**

In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/sample_car_sales_data.csv')
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  
0  Luxury model with premium features  
1    Low mileage, excellent condition  
2    Low mileage, excellent condition  
3        Clean interior, no accidents  
4    Low mileage, excellent condition

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
bow = CountVectorizer()
df_bow = bow.fit_transform(df["Description"])
print(df_bow)

  (0, 9)	1
  (0, 12)	1
  (0, 20)	1
  (0, 17)	1
  (0, 4)	1
  (1, 8)	1
  (1, 11)	1
  (1, 3)	1
  (1, 2)	1
  (2, 8)	1
  (2, 11)	1
  (2, 3)	1
  (2, 2)	1
  (3, 1)	1
  (3, 6)	1
  (3, 13)	1
  (3, 0)	1
  (4, 8)	1
  (4, 11)	1
  (4, 3)	1
  (4, 2)	1
  (5, 14)	1
  (5, 15)	1
  (5, 19)	1
  (5, 10)	1
  :	:
  (144, 14)	1
  (144, 15)	1
  (144, 19)	1
  (144, 10)	1
  (145, 18)	1
  (145, 16)	1
  (145, 5)	1
  (145, 7)	1
  (146, 9)	1
  (146, 12)	1
  (146, 20)	1
  (146, 17)	1
  (146, 4)	1
  (147, 8)	1
  (147, 11)	1
  (147, 3)	1
  (147, 2)	1
  (148, 18)	1
  (148, 16)	1
  (148, 5)	1
  (148, 7)	1
  (149, 8)	1
  (149, 11)	1
  (149, 3)	1
  (149, 2)	1


In [ ]:
df_bow = pd.DataFrame(df_bow.toarray(), columns = bow.get_feature_names_out())
df_bow.head()


accidents  clean  condition  excellent  features  fully  interior  loaded  \
0          0      0          0          0         1      0         0       0   
1          0      0          1          1         0      0         0       0   
2          0      0          1          1         0      0         0       0   
3          1      1          0          0         0      0         1       0   
4          0      0          1          1         0      0         0       0   

   low  luxury  ...  mileage  model  no  one  owner  package  premium  sport  \
0    0       1  ...        0      1   0    0      0        0        1      0   
1    1       0  ...        1      0   0    0      0        0        0      0   
2    1       0  ...        1      0   0    0      0        0        0      0   
3    0       0  ...        0      0   1    0      0        0        0      0   
4    1       0  ...        1      0   0    0      0        0        0      0   

   well  with  
0     0     1  
1     0     0  
2     0     0  
3     0     0  
4     0     0  

[5 rows x 21 columns]

In [ ]:
df.drop(columns=["Description"],inplace = True)


In [ ]:
df = pd.concat([df,df_bow],axis=1)
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  accidents  clean  \
0  23437         342   Honda  Accord   2023-03-13          0      0   
1  21723         264  Toyota   Prius   2023-06-14          0      0   
2  44113         351   Honda   Civic   2024-03-04          0      0   
3  48343         268   Honda    CR-V   2024-10-12          1      1   
4  28310         172    Audi      A3   2024-03-24          0      0   

   condition  excellent  features  ...  mileage  model  no  one  owner  \
0          0          0         1  ...        0      1   0    0      0   
1          1          1         0  ...        1      0   0    0      0   
2          1          1         0  ...        1      0   0    0      0   
3          0          0         0  ...        0      0   1    0      0   
4          1          1         0  ...        1      0   0    0      0   

   package  premium  sport  well  with  
0        0        1      0     0     1  
1        0        0      0     0     0  
2        0        0      0     0     0  
3        0        0      0     0     0  
4        0        0      0     0     0  

[5 rows x 26 columns]

Data normalization , Standardizatiom , Scaling

In [ ]:
#Min-Max Scaler
import pandas as pd
df = pd.read_csv('/content/sample_data/sample_car_sales_data.csv')
df.head()

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  
0  Luxury model with premium features  
1    Low mileage, excellent condition  
2    Low mileage, excellent condition  
3        Clean interior, no accidents  
4    Low mileage, excellent condition

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df["Normalized_Horsepower"] = scaler.fit_transform(df[["Horsepower"]])
df.head()

# x_scaled = (X - X.min(axis = 0)) / (X.max(axis = 0 )) - X.min(axis = 0)

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  Normalized_Horsepower  
0  Luxury model with premium features               0.805369  
1    Low mileage, excellent condition               0.543624  
2    Low mileage, excellent condition               0.835570  
3        Clean interior, no accidents               0.557047  
4    Low mileage, excellent condition               0.234899

In [ ]:
#Standard scaler (Data Standerization)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df["Standardized_Horsepower"] = scaler.fit_transform(df[["Horsepower"]])
df.head()
# z = (x - u) / s
# z = standardized value : x = original value : u = mean of training samples : s = std deviation

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  Normalized_Horsepower  \
0  Luxury model with premium features               0.805369   
1    Low mileage, excellent condition               0.543624   
2    Low mileage, excellent condition               0.835570   
3        Clean interior, no accidents               0.557047   
4    Low mileage, excellent condition               0.234899   

   Standardized_Horsepower  
0                 0.995471  
1                 0.112185  
2                 1.097389  
3                 0.157482  
4                -0.929640

In [ ]:
#Robust Scaler (Data Scaling)
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
df["Scaled_Horsepower"] = scaler.fit_transform(df[["Horsepower"]])
df.head()
# X_scaled = (X - Q2) / IQR
# Q1 - 25% ; Q2 - 50% ; Q3 - 75%
# IQR = Q3 - Q1

Price  Horsepower   Brand   Model Date_of_Sale  \
0  23437         342   Honda  Accord   2023-03-13   
1  21723         264  Toyota   Prius   2023-06-14   
2  44113         351   Honda   Civic   2024-03-04   
3  48343         268   Honda    CR-V   2024-10-12   
4  28310         172    Audi      A3   2024-03-24   

                          Description  Normalized_Horsepower  \
0  Luxury model with premium features               0.805369   
1    Low mileage, excellent condition               0.543624   
2    Low mileage, excellent condition               0.835570   
3        Clean interior, no accidents               0.557047   
4    Low mileage, excellent condition               0.234899   

   Standardized_Horsepower  Scaled_Horsepower  
0                 0.995471           0.523169  
1                 0.112185           0.056801  
2                 1.097389           0.576981  
3                 0.157482           0.080717  
4                -0.929640          -0.493274

Train Test Split

In [ ]:
#Load the dataset

import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
df["target"] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
#Holdout Method : Training set and Testing set  (80:20 ; 70:30 , 90:10)
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

X = df.drop(columns=["target"])
y = df["target"]

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy : ",accuracy)


Accuracy :  1.0


In [ ]:
#Cross validation method
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
scores = cross_val_score(clf,X,y,cv=5)

print("Cross-validation scores",scores)
print("Mean accuracy",np.mean(scores))

Cross-validation scores [0.96666667 0.96666667 0.9        1.         1.        ]
Mean accuracy 0.9666666666666668


Stratified sampling

In [ ]:
#Stratified sampling

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = df.drop(columns=["target"])
y = df["target"]


In [ ]:
#Making the target column imbalanced
y_imbalanced = np.where(y==2 , 0 , y)

In [ ]:
np.bincount(y_imbalanced)

array([100,  50])

In [ ]:
X_train , X_test , y_train , y_test = train_test_split(X,y_imbalanced,test_size=0.2,random_state=42)

clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy : ",accuracy)

Accuracy :  1.0


Train Validation Test Split

In [ ]:
#Train-Validation-Test-Split
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

#Load the dataset
iris = load_iris()
x = iris.data
y = iris.target

#Split the data into 80%(Training + Validation) and 20% for testing
X_train_val , X_test , y_train_val , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

#Split the training and validation data into 75%(Training) and 25%(Validation)
X_train , X_val , y_train , y_val = train_test_split(X_train_val,y_train_val,test_size=0.25,random_state=42)

#Train the model
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
#Initialize the testing with validation
y_val_pred = clf.predict(X_val)
accuracy_val = accuracy_score(y_val,y_val_pred)
print("Validation accuracy ",accuracy_val)

Validation accuracy  0.9


In [ ]:
#final testing with testing data (20%)
y_test_pred = clf.predict(X_test)
accuracy_test = accuracy_score(y_test,y_test_pred)
print("Testing accuracy ",accuracy_test)


Testing accuracy  0.9333333333333333
